title : 지속하여 생각하고 고민하는
name: '지속하여 생각하고 고민하는'
description: 'Simple, light weight, responsive jekyll theme for hackers'

markdown: kramdown
highlighter: rouge
javascript_enabled: true

featured_posts_title: Unrelated
featured_posts:
  - url: '#'
    title: 'Featured post #1'
  - url: '#'
    title: 'Featured post #2'
  - url: '#'
    title: 'Featured post #3'

collections:
  java:
    title: java
    default_open: true
    output: true
  spring:
    title: spring
    default_open: true
    output: true
  os:
    title: OS
    default_open: true
    output: true
  network:
    title: Network
    default_open: true
    output: true

defaults:
  - scope:
      type: posts
    values:
      title: Essays
      permalink: /post/:title
  - scope:
      type: news
    values:
      title: News
      permalink: /news/:title

plugins:
  - jekyll-sitemap
